server:
  port: 8089

--- #---------------------数据库配置---------------------------
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chirstmas?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 5436205
  redis:
    host: 127.0.0.1
    port: 6380
    password: 123456
  mail:
    # 配置 SMTP 服务器地址
    host: smtp.qq.com
    # 发送者邮箱
    username: 1126556181@qq.com
    # 配置密码，注意不是真正的密码，而是刚刚申请到的授权码
    password: qmfpdvzzdgywbaee
    # 端口号465或587
    port: 587
    # 默认的邮件编码为UTF-8
    default-encoding: UTF-8
    # 配置SSL 加密工厂
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#文件配置
chirstmas:
  file:
    upload:
      path: D:/Users/xuTao/upload
  cors:
    allow-origins:
      - http://localhost:8080
  jwt:
    secret:
      Of2cqnQ3A5UOCIjIdmlPmW5lxdfae5VnH2IVGPq0WnI